### Check connection to Orion context-broker
curl -iX GET http://localhost:1026/version

### Create Entities
# done in app.py create


### Query Entities
curl -iX GET 'http://localhost:1026/v2/entities?type=Sensor' \
    | jq '.'


### Delete all Entities
curl -iX DELETE 'http://localhost:1026/v2/entities?type=Sensor'


### Create a new attribute
curl -iX POST 'http://localhost:1026/v2/entities/urn:ngsi-ld:Sensor:A5.18/attrs' \
  --header 'Content-Type: application/json' \
  --data '{
      "Temperature_avg":{"value": 26.2},
      "Humidity_avg":{"value": 42.2},
      "CO2_avg":{"value": 656},
      "Pressure_avg":{"value": 995.1}
}'


### Check to see the new attributes
curl -X GET 'http://localhost:1026/v2/entities/urn:ngsi-ld:Sensor:A5.18'


### Create Subscription to receive notifications
curl -iX POST \
  'http://localhost:1026/v2/subscriptions/' \
  -H 'Content-Type: application/json' \
  -d '{
  "description": "Notify QuantumLeap of count changes of any Sensor",
  "subject": {
    "entities": [
      {
        "idPattern": ".*",
        "type": "Sensor"
      }
    ],
    "condition": {
      "attrs": [
        "Temperature_avg"
      ]
    }
  },
  "notification": {
    "http": {
      "url": "http://quantumleap:8668/v2/notify"
    },
    "attrs": [      
        "Temperature_avg",
        "Humidity_avg",
        "CO2_avg",
        "Pressure_avg"
    ],
    "metadata": ["dateCreated", "dateModified"]
  },
  "throttling": 1
}'


### Check Subscriptions
curl -X GET \
  'http://localhost:1026/v2/subscriptions/'



### Delete Subscription
curl -X DELETE \
  'http://localhost:1026/v2/subscriptions/668d384dfd28a7316e0f1d88' \





### QuantumLeap return an entity values
GET http://localhost:8668/v2/entities/urn:ngsi-ld:Sensor:F6.22

###
GET http://localhost:8668/v2/entities/urn:ngsi-ld:Sensor:A5.18


### QuantumLeap return First N sampled values
curl -X GET \
  'http://localhost:8668/v2/entities/urn:ngsi-ld:Sensor:A5.18/attrs/Temperature_avg?limit=3' \
  -H 'Accept: application/json'
