{
 "title": "A5.18 Workspace",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "A5.18 Workspace",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time_index, date_format(time_index), temperature, relativeHumidity, co2, atmosphericpressure FROM etindoorenvironmentobserved WHERE entity_id = 'urn:ngsi-ld:IndoorEnvironmentObserved:A5.18' ORDER BY time_index DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "A5.18 Workspace Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT replace(entity_id,'urn:ngsi-ld:IndoorEnvironmentObserved:','') as entity_name, latitude(location_centroid) as latitude, longitude(location_centroid) as longitude, location as geohash, * FROM etindoorenvironmentobserved WHERE entity_id = 'urn:ngsi-ld:IndoorEnvironmentObserved:A5.18' AND location IS NOT NULL LIMIT 1"
    }
   ]
  },
  {
   "title": "A5.18  Workspace Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT time_index, temperature FROM etindoorenvironmentobserved WHERE entity_id = 'urn:ngsi-ld:IndoorEnvironmentObserved:A5.18' ORDER BY time_index"
    }
   ]
  },
  {
   "title": "A5.18  Workspace Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT time_index, relativeHumidity FROM etindoorenvironmentobserved WHERE entity_id = 'urn:ngsi-ld:IndoorEnvironmentObserved:A5.18' ORDER BY time_index"
    }
   ]
  },
  {
   "title": "A5.18  Workspace CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT time_index, co2 FROM etindoorenvironmentobserved WHERE entity_id = 'urn:ngsi-ld:IndoorEnvironmentObserved:A5.18' ORDER BY time_index"
    }
   ]
  },
  {
   "title": "A5.18 Workspace Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "rawSql": "SELECT time_index, atmosphericpressure FROM etindoorenvironmentobserved WHERE entity_id = 'urn:ngsi-ld:IndoorEnvironmentObserved:A5.18' ORDER BY time_index"
    }
   ]
  }
 ]
}