apiVersion: 1

datasources:
  - name: CrateDB
    type: postgres
    access: proxy
    url: crate-db:5432
    database: doc
    user: crate
    password: ""
    sslmode: disable
    tlsAuth: false
    tlsAuthWithCACert: false
    editable: true
    jsonData:
      sslmode: disable
      tlsAuth: false
      tlsAuthWithCACert: false
